### ISSUE TITLE
happi integration

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#11]
As part of #3 we want to be able to inject from the server to the worker the devices and plans that are allowed.  To make sure that we never try to ship a "live" ophyd object between the processes, we should use happi as the device database.

**Comment by dmgav** [comment]
I assume that this functionality is mostly implemented: the plans and devices are imported from startup scripts or startup modules and permissions may be set to restrict direct access to plans and devices for user that belong to defined user groups. Startup scripts may also call API to load devices from Happi.
