### ISSUE TITLE
Option to submit metadata with a plan

### ISSUE THREAD

**Issue by dmgav** [bluesky/bluesky-queueserver#115]
Extend `queue_item_add` API to include optional `meta` key used to pass a dictionary or a list of dictionaries with plan metadata to Run Engine. If `meta` key contains a list of dictionaries, the list is merged into a single dictionary so that contents of a dictionary with the smallest index have higher priority (will overwrite key values from dictionaries with higher index). The option to keep metadata obtained from different sources in separate dictionaries may be convenient for some workflows. For example in HTTP server we may want to separate metadata into editable (entered by user) and non-editable (autogenerated) parts and keep the ability to edit the editable part and generate the autogenerated part, which could be easily achieved if they are kept in separate dictionaries.

**Comment by tacaswell** [comment]
Seems correct to me.

**Comment by dmgav** [comment]
Addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/116
