### ISSUE TITLE
Publish the parameters of a plan in a machine readable way

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#12]
To be able to (semi) auto generate UIs we need to be able to describe the parameters is a machine readable way (names, types, optional or not, etc ).  This has two parts:

 - pick a markup to send between the client and the server
 - start to annotate plans

**Comment by dmgav** [comment]
Custom decorator for annotating plans was implemented in https://github.com/bluesky/bluesky-queueserver/pull/68 The currently implemented features include tools for generation of complete plan parameter descriptions based on docstring, signature and description in the `parameter_annotation_decorator`. Separate issues will be created before work on refinement of the features will be performed.
