### ISSUE TITLE
qserver_list_of_plans_and_devices points to a malformed entrypoint

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-queueserver#125]
```
$ qserver_list_of_plans_and_devices -h
Traceback (most recent call last):
  File "/home/dallan/miniconda3/envs/py38/bin/qserver_list_of_plans_and_devices", line 33, in <module>
    sys.exit(load_entry_point('bluesky-queueserver', 'console_scripts', 'qserver_list_of_plans_and_devices')())
  File "/home/dallan/miniconda3/envs/py38/bin/qserver_list_of_plans_and_devices", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by dmgav** [comment]
As part of standardization of CLI parameter names I renamed `qserver_list_of_plans_and_devices` to `qserver-list-plans-devices`. Is it possible that `qserver_list_of_plans_and_devices` is left from old installation?
https://github.com/bluesky/bluesky-queueserver/blob/d96370b233fcb45e3ce992044dbc391be2c982af/setup.py#L51

**Comment by danielballan** [comment]
Oops, apologies for failing to follow up here. Yes, it was a stale installation.
