### ISSUE TITLE
thread configuration for redis host + port through start-re-server

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#127]
`PlanQueueOperations` is configurable at init time, but there is no way to push this information through the cli tool.

**Comment by dmgav** [comment]
Would it be sufficient to pass redis host name or IP with the default set to 'localhost'?

**Comment by tacaswell** [comment]
Yes.

**Comment by dmgav** [comment]
I will do it in the next PR.

**Comment by dmgav** [comment]
Addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/128
