### ISSUE TITLE
happi, but for plans

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#13]
Similar to #11 we need a clean way to specify what plans are available.  This may be as simple as 

```python

import importlib
module, name = plan_spec
plan = getattr(importlib.import(module), name)
```

but we may want to have a happi like database that would also store:

 - module / name
 - signature
 - comments for humans?
 - level of permission / danger of plan

**Comment by dmgav** [comment]
@tacaswell Do we really want to implement this? If we do, this would be a separate large project (comparable to Happi or an extension of Happi), not a component of the Queue Server.

**Comment by dmgav** [comment]
I guess I will close this issue for now.
