### ISSUE TITLE
priority vs FIFO queue

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#16]
Currently the queue is implemented as a FIFO queue (as a dequeue in memory of the server).  We should consider moving to a priority queue instead.  This could allow better collaboration between multiple humans and autonomous agents who are independently adding things to the queue.

**Comment by dmgav** [comment]
I think that the queue should be executed in deterministic order. Users should have ability to rearrange the order at any time (so it's not FIFO). Assigning priorities should be a GUI option that will rearrange the order of items in the queue. It may also be useful to schedule plan execution for specified time (e.g. for alignment scans). The scheduled scans should be executed at around the scheduled time, but without interruption of currently running scans. The scheduled scans are probably going to be added to the queue by autonomous agents.

**Comment by dmgav** [comment]
I believe the priority queue functionality could be achieved by sorting the queue using custom application-specific algorithms. It may be easy to provide wide choice of sorting options within the existing design and it is unlikely that standard be useful for too many practical applications. 

The issue can be reopened if needed.
