### ISSUE TITLE
using recv() in ReceiveConsoleOutputAsync and _socket.subscribe()

### ISSUE THREAD

**Issue by developingAlex** [bluesky/bluesky-queueserver#194]
Hi I'm successfully making use of the `recv` method in the `ReceiveConsoleOutputAsync` class in manager/output_streaming.py
However in order to successfully use it I found that I had to "reach into the class" and work with protected members,
specifically the `_socket.subscribe` call, which I'm calling manually when using the class, and my editor lints it telling me "Access to a protected member _socket of a class"
I noticed that it is used in the class when calling the `start()` method, but after reading the code and experimenting with that my understanding is that the `start` method is something you would use when you're taking the approach of supplying a callback function, but I'm taking the approach of manually calling the `.recv()` method, but it seems like the `.subscribe` needs to be done before the `.recv()` method will work, but if I call the `.start()` method (in order to achieve setting up the subscription so that the `.recv()` method then works) I end up with I believe another coroutine also consuming from the same socket, 
and the issue I get with this is that I believe there is then a bit of a race condition and if my manual call to `recv()` had no timeout (wait forever) it still raises a timeout if the other coroutine consumed the ?event? / ?message? before it was able to and then it returns 0 which I saw the documentation for pyzmq states it should only do when it has a timeout, yet I'm setting `timeout=None`,

Sorry for the wall of text, if it helps I could try and put together a minimal example to demonstrate the issue, but I'm hoping you could just take a second to look at the code implementation of the `ReceiveConsoleOutputAsync` class and let me know if yes it should be updated (possibly just a public "subscribe" and "unsubscribe" methods?) or no I'm using it wrong and I shouldn't have to "reach into it" and subscribe the socket to get the `.recv()` method to work?

**Comment by dmgav** [comment]
I don't see any issues with adding public `subscribe` and `unsubscribe` methods. It may be a bit confusing though, because one would have to use either of two options: subscribe/unsubscribe manually and use `recv` method or supply the callback function and use `start`/`stop` methods, but not mix two. So it must be properly documented with some example code.

**Comment by developingAlex** [comment]
Or maybe one solution might be if `recv()` is called and the socket isn't subscribed, then it subscribes it, and then `stop()` can be called if it needs to be unsubscribed, (if you wanted to keep the `recv()` option)

**Comment by dmgav** [comment]
Addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/224
