### ISSUE TITLE
RE-mimic CLI to talk to queue server

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#20]
Provide a restor that mimics the current feel of the RE, but instead of having the plans / devices in the user's process, it has proxies that on `RE(plan(...))` does the correct PUT to the queue server and waits for that plan to return.

We may want to build on this and have a non-blocking version of this as well for scripting purposes / use in autonomous agents (but how closely we want to mimic the current feel in that case is debatable).

**Comment by dmgav** [comment]
It is questionable whether we may want to implement API to mimic behavior of RE in IPython. It is unlikely that the remote RE interface will fully replicated RE running locally and partial implementation will simply confuse users. Currently available API are sufficient to control the queue from scripts or by autonomous agents.

The issue may be reopened if needed.
