### ISSUE TITLE
Sub devices are not understood by the qserver

### ISSUE THREAD

**Issue by whs92** [bluesky/bluesky-queueserver#208]
## Expected Behavior
I would like to be able to create a device with sub components like this:

```python
class StageXY(Device):
    x = Cpt(EpicsMotor, ':X')
    y = Cpt(EpicsMotor, ':Y')

stage = StageXY('STAGE_PV', name='stage')
```

And then call a plan with the qserver like this:

`qserver queue add plan '{"name":"scan", "args":[["det1", "det2"], "stage.x", -1, 1, 10]}'`

And then the plan be executed. I would like to use this syntax becuase it's the same as the syntax used in the non-qserver world like

`RE(scan([det1,det2],stage.x,-1,1,10))`

## Current Behavior
The plan and device is currently accepted by the qserver, but then the plan fails because the string `stage.x` is interpretted as a string and not as a device. For a `count` plan the error looks something like this

```
    _md = {'detectors': [det.name for det in detectors],
AttributeError: 'str' object has no attribute 'name'
INFO:bluesky_queueserver.manager.manager:Returning current queue and running plan ...
INFO:bluesky_queueserver.manager.manager:Returning the list of runs for the running plan ...
INFO:bluesky_queueserver.manager.manager:Returning plan history ...
```

## Possible Solution
@dmgav has suggested one solution is to define names in the global namespace in the startup files used by the RE worker. In the example above this would be something like

```python
stage_x = stage.x
stage_y = stage.y
```

The plans can then be called as follows:

`qserver queue add plan '{"name":"scan", "args":[["det1", "det2"], "stage_x", -1, 1, 10]}'`

This solves the immediate problem, but is slightly unobvious to users who didn't know about it since it differs from the syntax used in the IPython environment for calling devices. 

@tacaswell suggested allowing access to every subdevice of a device and improving the string -> object logic. 

While it lasts in slack here is the original thread: https://nikea.slack.com/archives/C7QC41C1G/p1642443219007300

**Comment by dmgav** [comment]
The issue was addressed in PRs https://github.com/bluesky/bluesky-queueserver/pull/209 and  https://github.com/bluesky/bluesky-queueserver/pull/210
