### ISSUE TITLE
HIGH-PRIORITY: Tutorial missing basic info to get started

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky-queueserver#211]
The [Tutorial (Demo)](https://blueskyproject.io/bluesky-queueserver/tutorial.html) is missing many of the basic sections needed to begin testing the bluesky-queueserver.  Since this software has caught the attention of many light sources, providing _something_ in this documentation is a very high priority.

**Comment by dmgav** [comment]
@prjemian I am planning to write those sections as my next step.

**Comment by prjemian** [comment]
Looking through the `profile_collection_sim` for pointers on how to describe the controls. Looks like my normal devices need to be decorated with a dictionary that provides guidance to the server, right?

**Comment by prjemian** [comment]
So my next thing to understand is how to I provide that info when I start a server.  I want to try it with a few of my devices and local plans.

**Comment by prjemian** [comment]
With those decorations, something will generate the `existing_plands_and_devices.yaml` file for me.

**Comment by prjemian** [comment]
This is useful for learning the options when starting the RE Manager: `start-re-manager -h`

This is the tool to interact with the RE Manager: `qserver`

**Comment by prjemian** [comment]
Next, is there something to help generate the dictionaries used in the decorators?

These are the simplest things to document first, I believe.  Some is in the repository's [`README.rst`](/README.rst) file.

**Comment by dmgav** [comment]
In principle, the `parameter_annotation_decorator` is optional. You can use plans without decorators. If parameter has no type annotation (annotation in plan header counts as type annotation), then the preprocessing algorithm will try to convert each string passed as a parameter value to a plan or device object. I tried to document the default behavior in https://blueskyproject.io/bluesky-queueserver/plan_annotation.html#plans-without-annotation-default-behavior 

Starting with v0.0.9 you don't need to generate `exisitng_plans_and_devices.yaml`. It will be generated automatically once you start the environment the first time and it will be updated automatically if you change the code. (`profile_collection_sim`, which is part of the repository, is updated automatically, but if you copy it to some other location, it will be updated). You need to copy `user_group_permissions.yaml` to the directory of startup files. 

There is a tool https://blueskyproject.io/bluesky-queueserver/cli_tools.html#qserver-list-plans-devices that generates `existing_plans_and_devices.yaml`. It is not necessary to use it, but I find it more convenient in debugging the issues with startup files. It is using exactly the same code to load startup files as the Queue Server.

Please let me know if you have any questions.

**Comment by prjemian** [comment]
Found this page mentioned on Slack: https://github.com/BCDA-APS/bluesky_training/blob/main/resources/demo-bluesky-queueserver.md

You added this important caveat:

> The only problem is that we probably should not teach users to shut down the server (`qserver manager stop safe on`), because this command literally makes the application to exit. The command is very useful for writing unit tests and may be in some cases for system administration, but general users should not shut down the server, especially if it is running as a service.

**Comment by dmgav** [comment]
I don't think users are going to be using CLI interface in production systems. CLI is more for testing and evaluation. I started another project https://github.com/bluesky/bluesky-queueserver-api which will eventually contain more convenient set of API (compatible Python API for 0MQ and HTTP) that potentially could be used from IPython. I did some work on it in my fork, but it did not reach the point when I can make the first PR.

**Comment by prjemian** [comment]
You were pointing out that the documentation has different audiences. One
is the user, the other is the administrator. Could be separate pages in the
docs.

**Comment by whs92** [comment]
Can we help edit/ review this? We might be able to help with a fresh pair of eyes that has also been working with the qserver

**Comment by dmgav** [comment]
@whs92 @prjemian Thanks, I will include you in the list of reviewers for the documentation PRs.

**Comment by prjemian** [comment]
Since this issue was opened, the documentation has advanced, enough that I have a [working first implementation](https://github.com/BCDA-APS/bdp_controls/pull/14).  I don't see a PR or any commits that reference this issue but believe the work to date has satisfied the issue.

**Comment by prjemian** [comment]
The BDP project has a [README](https://github.com/BCDA-APS/bdp_controls/blob/bf788e077928904145375527838a73579fe2bb09/qserver/README.md) that advises how to run and interact with `bluesky-queueserver`, `queue-monitor`, and `tiled`.

**Comment by prjemian** [comment]
I consider the issue resolved.  Thanks!
