### ISSUE TITLE
timestamp for each history item

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky-queueserver#225]
History, it's all about what and when.  Here, the history is missing the timestamps.

## Expected Behavior
Want to know *when* each item in the queueserver history was marked.

## Current Behavior

Queue history JSON documents do not show a `time` when the item was recorded.  Such as this fragment (from `qserver history get`):

```py
           {'args': [],
            'item_type': 'plan',
            'item_uid': '1b990152-b9d4-4e6e-8eb5-fea2df001291',
            'kwargs': {},
            'name': 'close_shutter',
            'result': {'exit_status': 'completed', 'run_uids': []},
            'user': 'GUI Client',
            'user_group': 'admin'},
           {'args': [],
            'item_type': 'plan',
            'item_uid': 'f7fdec6a-a3f7-414d-b925-ec30ce55e78f',
            'kwargs': {'atime': 0.5,
                       'md': {'frame_type': 'dark',
                              'task': 'demonstrate the qserver'}},
            'name': 'take_image',
            'result': {'exit_status': 'completed',
                       'run_uids': ['d7be982d-8879-41c9-ad95-2b8891b65aca']},
            'user': 'GUI Client',
            'user_group': 'admin'},
           {'args': [],
            'item_type': 'plan',
            'item_uid': '9bf1e5e9-43df-4320-a616-802a32b76209',
            'kwargs': {'x': 0, 'y': 0},
            'name': 'move_fine_positioner',
            'result': {'exit_status': 'completed', 'run_uids': []},
            'user': 'GUI Client',
            'user_group': 'admin'},
```

## Possible Solution

Add `item["time"] = time.time()` (or `item["result"]["time"] = time.time()`) after this line: https://github.com/bluesky/bluesky-queueserver/blob/7c150bbf9dd070a2b82ea10dfdd25be1f42ee404/bluesky_queueserver/manager/plan_queue_ops.py#L1431

**Comment by prjemian** [comment]
Or add to the `results` dictionary directly: https://github.com/bluesky/bluesky-queueserver/blob/7c150bbf9dd070a2b82ea10dfdd25be1f42ee404/bluesky_queueserver/manager/plan_queue_ops.py#L1008

**Comment by prjemian** [comment]
... and https://github.com/bluesky/bluesky-queueserver/blob/7c150bbf9dd070a2b82ea10dfdd25be1f42ee404/bluesky_queueserver/manager/plan_queue_ops.py#L1013

**Comment by dmgav** [comment]
Originally it was assumed that time for each run could be extracted from Data Broker, but I think it may be useful to add time to `result`.

**Comment by dmgav** [comment]
Addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/227

**Comment by dmgav** [comment]
The issue was resolved. Timestamps were added to the history items.

**Comment by prjemian** [comment]
Thanks!
