### ISSUE TITLE
baseline and monitor streams

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky-queueserver#228]
How to setup baseline devices or supplementary monitor streams?

**Comment by prjemian** [comment]
Possibly, wrap each supported plan with [`@baseline_decorator`](https://blueskyproject.io/bluesky/generated/bluesky.preprocessors.baseline_decorator.html) and/or [`@monitor_during_decorator`](https://blueskyproject.io/bluesky/generated/bluesky.preprocessors.monitor_during_decorator.html) and accept those devices & signals as arguments to the custom plan.

Is this the way to proceed with the standard `bluesky.plans`?

**Comment by prjemian** [comment]
That is **exactly** the beast with which I am wrestling, the separation of our rich setup of a console or notebook experience from the startup of the queueserver which may not be able to undo all of our console planning.  I'll proceed with the `--keep-re` option and continue extracting the other UI features (such as `BestEffortsCallback` and what commands are added to the user's interactive experience).  I'm rather attached to our custom logging, implemented with features requested by our beam line users.  Maybe that can be preserved, maybe not.

**Comment by dmgav** [comment]
In startup scripts you can use conditional statements based on `bluesky_queueserver.is_re_worker_active()` (https://github.com/bluesky/bluesky-queueserver/blob/613cfab2db31b6f43b73aa866c5f81f7d1acbc08/bluesky_queueserver/manager/profile_tools.py#L319-L343) to enable/disable blocks of code when it is running in RE worker.

**Comment by dmgav** [comment]
I think custom logging should work with the Queue Server. RE Worker should be able to run any reasonable code.

**Comment by ksunden** [comment]
https://github.com/wright-group/bluesky-in-a-box/blob/main/re-manager/startup.py#L37-L50

This is what we do, just wrap all of our plans with baseline decorator

**Comment by prjemian** [comment]
My questions are answered.  Thanks.
