### ISSUE TITLE
Request: Supported method for relating queue item execution to runs

### ISSUE THREAD

**Issue by klauer** [bluesky/bluesky-queueserver#237]
## Expected Behavior
I would like to be able to submit an item to the queue, have it executed, and then be able to match up the queue item's execution with live and/or previously-acquired data.

* The existing implementation is ideally suited for user-queued items - with a human in the loop somewhere.
* I am looking toward programmatically queued items and higher-level automation of the queue.
* I believe the queue server (or Python-facing API, perhaps) should natively support something along these lines.

## Current Behavior
My understanding is that there is no standardized way. It's up to the user to add in metadata for their queue items to try to match them with runs.

**Comment by dmgav** [comment]
Mapping from item UIDs to run UIDs already exists in item history. I understand that you are interested in mapping from run UIDs to queue item UIDs. It should be technically easy to add queue item UIDs to run metadata automatically in a standard way. The run start document of each run will contain item UID at a predefined place. Would this be sufficient? 

The other option, which does not exclude the first, is to generate the mapping locally from downloaded plan history. This will not require access to databroker and if considered generally useful, it could be added to the API. But this is rather trivial transformation.
