### ISSUE TITLE
Launch worker from server

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#3]
The API server should be able to launch / exit / restart the worker process.  The worker process should not be externally configure, but should build its state from the information pushed in by the API server.   Currently you have to start the plan "manually".

The information pushed in should include (but not limited to):

 - what plans should be available in the namespace
 - what devices should be available in the namespace
 - where to publish the documents to
 - where to publish logs to

Maybe should inculde:
 - where to pull the the "next run id" from

Should not include:
 - user / sample metadata (this belongs to the server and should be pushed in with every plan)

We also should use this to set up a two-way communication between the worker and the server.

Candidates for how to manage the worker process:
 - systemd/supervisord tasks (not quite sure how to do the information injection but I assume it is possible)
 - `Subprocess`
 - `multiprocess.Process`

The worker should remain its own process not a thread so we can restart it from the API server, and we may want to eventually run the worker on a different machine than the API server.

**Comment by dmgav** [comment]
Most of the described features were implemented in PR https://github.com/bluesky/bluesky-queueserver/pull/29 and improved in multiple following PRs.
