### ISSUE TITLE
Bluesky plan_stubs not recognized with Bluesky v1.13.0a4

### ISSUE THREAD

**Issue by canismarko** [bluesky/bluesky-queueserver#305]
## Expected Behavior

If I import bluesky plan stubs in my queueserver startup file, they should be available in the queueserver as plans. This was the behavior when using bluesky v1.13.0a3 and below.

## Current Behavior

The plan stubs are not available.

## Possible Solution

Queueserver uses ``inspect.isgeneratorfunction()`` to determine if a token corresponds to a valid plan. With bluesky v1.13.0v4, plan stubs are now wrapped and no longer pass this check.

@tacaswell's suggestion is to include a separate check to detect these wrapped plan stubs: https://github.com/bluesky/bluesky/issues/1779#issuecomment-2267222073

## Steps to Reproduce (for bugs)

1. Install Bluesky v1.13.0a4
2. Write a queuerserver startup file that imports ``from bluesky.plan_stubs import mv``
3. Start the queueserver
4. Look at the list of available plans.

## Context

We use the queueserver for executing scans at our beamline. We include a few plan stubs for making adjustments to the beamline in-line in the queue.

## Your Environment

https://gist.github.com/canismarko/39d39055a71b165faba801872162f7ba

**Comment by canismarko** [comment]
Fixed: https://github.com/bluesky/bluesky/pull/1780

**Comment by dmgav** [comment]
Resolved in https://github.com/bluesky/bluesky-queueserver/pull/306

**Comment by canismarko** [comment]
I've been using this successfully for the past few weeks, so I think everything is good. Closing this issue now. Thank you!
