### ISSUE TITLE
publish logs

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#5]
Based on how we pass configuration in via #3 we should publish out (verbose) logs from the worker.  As we are running the plans in a worker behind a server we are losing much of our visibility in to the process which needs to be replaced by logging.

We may want additional logging above what is currently in the RE.

**Comment by dmgav** [comment]
The feature implemented in https://github.com/bluesky/bluesky-queueserver/pull/174 allows to monitor full console output of RE Manager remotely. Bluesky logs may be saved using standard mechanism defined in `nslsii`.
