### ISSUE TITLE
select communication channel between the worker and the API server

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#6]
Currently the worker plan polls the API server for the next plan (and sleeps for some period of time if there is no work) and there is no feedback from the worker to API server that anything is happening.

Some of this will be handled by #5  or by the API server subscribing to the document firehose, but we probably want an additional bi-directional and lower volume communication channel between the worker and the API server to carry information such as:

 - the next plan to run
 - interruptions / cancellations 
 - heart beat
 - currently running a plan / idle
 - what plans / devices are or should be available
 - last finished plan (?)

This is not a priority for the MVP1

**Comment by dmgav** [comment]
The issue is out of date. Communication between HTTP server, RE Manager and RE Worker was implemented in PR https://github.com/bluesky/bluesky-queueserver/pull/31 and evolved since then.
