### ISSUE TITLE
Develop the vocabulary between the server and the worker

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#7]
Currently the only communication between the worker and the sever is "next plan please".  We will presumable need a richer language to support : 

 - the next plan to run
 - interruptions / cancellations 
 - heart beat
 - currently running a plan / idle
 - what plans / devices are or should be available
 - ??

This could be a single channel with many message types or this could be many dedicated channels?

**Comment by dmgav** [comment]
HTTP server communicates with RE Manager/Worker via ZMQ. One of implementations of API can be found in PR https://github.com/bluesky/bluesky-queueserver/pull/75. API evolved since then.
