### ISSUE TITLE
Add support for cancellation / interruption 

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#8]
We need to add a way for the API server to stop / abort / halt the currently running run.

This could be done several ways:

 - suspender-like (aka killers) + a dedicated PV
 - actually sending SIGINT(s) to the worker process
 - some other push mechanism on the worker-server communication channel

**Comment by dmgav** [comment]
Addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/30
