### ISSUE TITLE
Extra testing requirements

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-queueserver#84]
Should these come in through `requirements-dev.txt` instead of being separately installed in the workflow?

https://github.com/bluesky/bluesky-queueserver/blob/9105035990256b9894892d51c5ce9148f3ee87ae/.github/workflows/testing.yml#L25-L26

**Comment by dmgav** [comment]
Addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/101
