### ISSUE TITLE
Upgraded packages in testing workflow

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-queueserver#85]
Does the default `python` come with `setuptools` installed? What about `numpy`? On Travis it _does_ and so we have learned that updating both of these, as well as pip, helps avoid installation issues.

https://github.com/bluesky/bluesky-queueserver/blob/9105035990256b9894892d51c5ce9148f3ee87ae/.github/workflows/testing.yml#L22

**Comment by dmgav** [comment]
Addressed in https://github.com/bluesky/bluesky-queueserver/pull/101
