### ISSUE TITLE
Docs should be pushed to bluesky/bluesky.github.io repo

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky-queueserver#86]
There are two ways to publish to the documentation for GH pages: by pushing to a special branch of each repo (`gh-pages` by convention, but configurable) or by pushing to a central repo with a special name, `ORG_NAME.github.io`. For the bluesky org it's https://github.com/bluesky/bluesky.github.io.

For example, in the bluesky/bluesky CI, we configure doctr to build the bluesky docs and push them to the `master` branch of bluesky/bluesky.github.io under the subdirectory bluesky.

```
      doctr deploy --deploy-repo bluesky/bluesky.github.io --deploy-branch-name master bluesky;
```
Source: https://github.com/bluesky/bluesky/blob/888716e078dcc0f0479c0583e7a1a940af3f2524/.travis.yml#L110

The advantage of this approach is that all the static assets are in one place and not polluting the respective repos; they can stay lean. GitHub allows you to mix approaches if you want, with some repos having a `gh-pages` branch and some repos not, which is why blueskyproject.io/bluesky routes to the static assets in bluesky.github.io/bluesky and blueskyproject.io/bluesky-queueserver routes to the static assets in the gh-pages branch of bluesky-queueserver.

For the sake of keeping things consistent across the project, I think we should update the Action to push to bluesky.github.io.

**Comment by dmgav** [comment]
@danielballan Did you implement it with GitHub Actions for another repository? Is there more to it than checking out https://github.com/bluesky/bluesky.github.io, replacing the contents of the particular directory (say `/bluesky-queueserver`) and pushing the changes?

**Comment by mrakitin** [comment]
As a side note, I was able to use `doctr` without Travis by setting some environment variables in my local environment while debugging the documentation update for `hklpy` (https://github.com/bluesky/hklpy/pull/35 and https://github.com/bluesky/hklpy/pull/39/).

**Comment by dmgav** [comment]
Addressed in PR https://github.com/bluesky/bluesky-queueserver/pull/101
