### ISSUE TITLE
Harden the plan request -> plan + objects code

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky-queueserver#9]
Currently we bind a dictionary of plans and a dictionary of devices and (rather naively) use that to covert a json document -> runnable plans.  If things go wrong (i.e. we get a plan or object we were not expecting) we explode.  We need to:

 - not exit the worker if there is bad input
 - provide some feedback to the API server (xref #7 ) if there is bad input
 - validate the input before we go looking for python objects
 - do our utmost to never exec or eval

**Comment by dmgav** [comment]
Current implementation of RE Manager supports safe submission of plans to RE Worker including validation of plan parameters. Plan failures is also handled safely within RE Worker. Failed plan could be restarted or removed from the queue.
