### ISSUE TITLE
queue_clear

### ISSUE THREAD

**Issue by gwbischof** [bluesky/bluesky-queueserver#99]
The docs says:
qserver -c queue-clear

and also:
qserver -c history_clear

should queue-clear be queue_clear?

**Comment by dmgav** [comment]
Changes introduced in PR https://github.com/bluesky/bluesky-queueserver/pull/98 change the structure of the parameters of for `qserver` CLI tools. 

```
qserver -c queue_clear
qserver -c history_clear
```

are replaced by

```
qserver queue clear
qserver history clear
```

**Comment by dmgav** [comment]
Addressed in https://github.com/bluesky/bluesky-queueserver/pull/98
